<?

$config["nano_navigation"]["redirects"] = array(
	"formstone"            => "http://formstone.it",
	"formstone/boxer"      => "http://formstone.it/components/boxer",
	"formstone/gridlock"   => "http://formstone.it/components/gridlock",
	"formstone/macaroon"   => "http://formstone.it/components/macaroon",
	"formstone/mimeo"      => "http://formstone.it/components/mimeo",
	"formstone/naver"      => "http://formstone.it/components/naver",
	"formstone/pager"      => "http://formstone.it/components/pager",
	"formstone/picker"     => "http://formstone.it/components/picker",
	"formstone/pronto"     => "http://formstone.it/components/pronto",
	"formstone/ranger"     => "http://formstone.it/components/ranger",
	"formstone/roller"     => "http://formstone.it/components/roller",
	"formstone/rubberband" => "http://formstone.it/components/rubberband",
	"formstone/scout"      => "http://formstone.it/components/scout",
	"formstone/scroller"   => "http://formstone.it/components/scroller",
	"formstone/selecter"   => "http://formstone.it/components/selecter",
	"formstone/shifter"    => "http://formstone.it/components/shifter",
	"formstone/sizer"      => "http://formstone.it/components/sizer",
	"formstone/stepper"    => "http://formstone.it/components/stepper",
	"formstone/tabber"     => "http://formstone.it/components/tabber",
	"formstone/tipper"     => "http://formstone.it/components/tipper",
	"formstone/wallpaper"  => "http://formstone.it/components/wallpaper",
	"formstone/zoetrope"   => "http://formstone.it/components/zoetrope",
	"formstone/zoomer"     => "http://formstone.it/components/zoomer",

	"projects"             => "http://formstone.it",
	"projects/boxer"       => "http://formstone.it/components/boxer",
	"projects/gridlock"    => "http://formstone.it/components/gridlock",
	"projects/macaroon"    => "http://formstone.it/components/macaroon",
	"projects/mimeo"       => "http://formstone.it/components/mimeo",
	"projects/naver"       => "http://formstone.it/components/naver",
	"projects/pager"       => "http://formstone.it/components/pager",
	"projects/picker"      => "http://formstone.it/components/picker",
	"projects/pronto"      => "http://formstone.it/components/pronto",
	"projects/ranger"      => "http://formstone.it/components/ranger",
	"projects/roller"      => "http://formstone.it/components/roller",
	"projects/rubberband"  => "http://formstone.it/components/rubberband",
	"projects/scout"       => "http://formstone.it/components/scout",
	"projects/scroller"    => "http://formstone.it/components/scroller",
	"projects/selecter"    => "http://formstone.it/components/selecter",
	"projects/shifter"     => "http://formstone.it/components/shifter",
	"projects/sizer"       => "http://formstone.it/components/sizer",
	"projects/stepper"     => "http://formstone.it/components/stepper",
	"projects/tabber"      => "http://formstone.it/components/tabber",
	"projects/tipper"      => "http://formstone.it/components/tipper",
	"projects/wallpaper"   => "http://formstone.it/components/wallpaper",
	"projects/zoetrope"    => "http://formstone.it/components/zoetrope",
	"projects/zoomer"      => "http://formstone.it/components/zoomer"
);

?>